### ISSUE TITLE
ChatGPT 3.5

### ISSUE THREAD

**Issue by MPagliari** [TabulateJarl8/randfacts#13] opened 2023-04-02 13:04 UTC
I believe ChatGPT 3.5 is relying heavily on this repository. OpenAI may even be catching queries for facts directly and intercepting it to reply almost directly from here.
one it tends to like is this one:
- Did you know that the shortest war in history was between Zanzibar and Great Britain in 1896? The war lasted just 38 minutes.
- The shortest war in recorded history was between Britain and Zanzibar on August 27, 1896. The war lasted only 38 minutes.
- The shortest war in history was between Zanzibar and Britain in 1896 and lasted only 38 minutes.

**Comment by TabulateJarl8** [comment] 2023-04-02 20:20
The model is trained on the internet so this makes sense. It may also have collected data from other websites, as many of the facts in randfacts have been collected from other sites. This isn't just one site either. Since these are facts, many different "random fact" websites will include the same or similar facts, which would reinforce this information for GPT 3.5. Since this is an open source project licensed under MIT, I don't see what the issue is, could you elaborate?

**Comment by TabulateJarl8** [comment] 2023-04-14 03:28
Closing this issue as it seems irrelevant. Will reopen if deemed necessary after further elaboration

**Closed as completed by TabulateJarl8** 2023-04-14 03:28 UTC
